export  const ADD_ORDER_ITEM ="ADD_ORDER_ITEM";
export  const DELETE_ORDER_ITEM ="DELETE_ORDER_ITEM";

export  const SET_USER_LOGIN ="SET_USER_LOGIN";
export  const DELETE_USER_LOGIN ="DELETE_USER_LOGIN";

